"""Pydantic v2 schemas for investigations and lifecycle management.

Full implementation is covered by task 2.1.
"""

# TODO: implement — task 2.1
# class InvestigationStatus(str, Enum): OPEN, UNDER_REVIEW, CLOSED
# class Investigation(BaseModel): ...
# class CreateInvestigationPayload(BaseModel): ...
# class OutcomePayload(BaseModel): ...
# class NotePayload(BaseModel): ...
